export const TYPES = {
    READ_STATE: "READ_STATE",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ONE_PRODUCT: "REMOVE_ONE_PRODUCT",
    REMOVE_ALL_PRODUCT: "REMOVE_ALL_PRODUCT",
    CLEAR_CART: "CLEAR_CART",
    ADD_TO_FAV: "ADD_TO_FAV",
    REMOVE_FAV: "REMOVE_FAV"
}